# 워크플로우 이름
name: Deploy Spring Boot & React to EC2

# 워크플로우 실행 트리거 설정: main 브랜치에 push 이벤트가 발생했을 때 실행
on:
  push:
    branches: [ "main" ]

# 실행될 작업(Job) 정의
jobs:
  build-and-deploy:
    # 작업이 실행될 가상 머신 환경
    runs-on: ubuntu-latest

    # 작업의 단계(Step)들
    steps:
      # 1. 소스 코드 체크아웃
      - name: Checkout source code
        uses: actions/checkout@v4

      # 2. JDK 21 (Amazon Corretto) 환경 설정
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'

      # 3. Node.js 20.x 환경 설정 (npm 의존성 캐싱 포함)
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      # 4. gradlew 스크립트에 실행 권한 부여
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
        working-directory: ./BackEnd

      # 5. Gradle을 이용한 프로젝트 빌드 (테스트 제외)
      - name: Build with Gradle
        run: ./gradlew build -x test --no-daemon
        working-directory: ./BackEnd
        
      # 6. EC2에 배포된 기존 JAR 파일 삭제
      - name: Clean up old artifacts on EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: ${{ secrets.EC2_PORT }}
          script: |
            # 기존에 배포되어 있던 JAR 파일을 삭제합니다.
            rm -f /home/ubuntu/app/*-SNAPSHOT.jar
            echo "Old JAR file deleted."

      # 7. GCP 키 파일을 EC2 인스턴스에 생성 (SSH를 통해)
      - name: Create GCP credentials file on EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: ${{ secrets.EC2_PORT }}
          script: |
            # GitHub Secrets 값을 EC2의 지정된 경로에 파일로 생성합니다.
            echo "${{ secrets.GCP_SA_KEY_JSON }}" > /home/ubuntu/app/gcp-key.json
            echo "GCP key file created."

      # 8. 빌드된 JAR 파일을 EC2 인스턴스로 복사 (SCP)
      - name: Transfer JAR to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: ${{ secrets.EC2_PORT }}
          source: "BackEnd/build/libs/*-SNAPSHOT.jar"
          target: "/home/ubuntu/app"

      # 9. EC2 인스턴스에서 애플리케이션 실행 스크립트 실행 (환경 변수 설정 및 로그 파일 생성)
      - name: Execute deployment script on EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: ${{ secrets.EC2_PORT }}
          script: |
            # 기존에 실행 중이던 Java 애플리케이션 프로세스를 종료합니다.
            pgrep java | xargs kill -9 || true
            
            # GOOGLE_APPLICATION_CREDENTIALS 환경 변수를 설정합니다.
            export GOOGLE_APPLICATION_CREDENTIALS=/home/ubuntu/app/gcp-key.json
            
            # 새로 배포된 JAR 파일을 백그라운드에서 실행하고, app.log 파일에 로그를 기록합니다.
            nohup env GOOGLE_APPLICATION_CREDENTIALS=$GOOGLE_APPLICATION_CREDENTIALS java -jar /home/ubuntu/app/*-SNAPSHOT.jar > /home/ubuntu/app/app.log 2>&1 &

